name: vault-dynamic-secrets

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Retrieve Vault Dynamic Database Secrets
        id: vault-database-secrets
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault-cluster-aws.vault.797ef198-e9b5-4477-b448-5c560fcbe367.aws.hashicorp.cloud:8200
          token: ${{ secrets.VaultToken }}
          namespace: admin
          secrets: |
            /database/creds/ddb-rds-role  # Adjust the Vault path to match your setup
          method: token
          kubernetesTokenPath: /var/run/secrets/kubernetes.io/serviceaccount/token
          exportEnv: true
          exportToken: false
          outputToken: false
          tlsSkipVerify: false
          jwtTtl: 3600
          ignoreNotFound: false

      - name: Display Vault Database Secrets
        run: |
          echo "Database username: $DATABASE_USERNAME"
          echo "Database password: $DATABASE_PASSWORD"

      - name: Set Output Database Secrets
        run: |
          echo "::set-output name=database_username::$DATABASE_USERNAME"
          echo "::set-output name=database_password::$DATABASE_PASSWORD"

      - name: Use Output Database Secrets
        run: |
          echo "Database username retrieved from Vault: ${{ steps.vault-database-secrets.outputs.database_username }}"
          echo "Database password retrieved from Vault: ${{ steps.vault-database-secrets.outputs.database_password }}"
